# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: users_service.proto for package 'demo'

require 'grpc'
require 'users_service_pb'

module Demo
  module Users
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'demo.Users'

      rpc :Find, FindUserRequest, User
      rpc :All, AllUserRequest, AllUserReply
    end

    Stub = Service.rpc_stub_class
  end
end
